---
- name: Check for docker-machine binary.
  stat:
    path: "{{ docker_machine_install_path }}/docker_machine"
    follow: yes
  register: dm_binary

- name: Download ca-certificates
  package:
    name: ca-certificates
    state: installed

- name: Download docker-machine binary.
  get_url:
    url: "https://github.com/docker/machine/releases/download/v{{ docker_machine_version }}/docker-machine-{{ ansible_system }}-{{ ansible_machine }}"
    dest: "{{ docker_machine_install_path }}/docker-machine"
    owner: root
    group: root
    mode: 0755
  when: not dm_binary.stat.exists

- name: Check for docker-machine bash completion.
  stat:
    path: "/etc/bash_completion.d/docker"
  register: dm_bash_completion

- name: Install docker-machine bash completion.
  get_url:
    url: https://raw.githubusercontent.com/docker/docker-ce/master/components/cli/contrib/completion/bash/docker
    dest: /etc/bash_completion.d/docker
    owner: root
    group: root
    mode: 0644
  when: not dm_bash_completion.stat.exists
